improved error handling for incomplete golem installs

diff --git a/gc_golem b/gc_golem
--- a/gc_golem
+++ b/gc_golem
@@ -7,13 +7,17 @@
 # install to $HOME/.local/share/bash-completion/completions/golem
 
 YAGNA_COMPLETION_ENGINE=$(yagna complete bash 2>&1)	# store the completion engine script produced by yagna
-source /dev/stdin <<<$YAGNA_COMPLETION_ENGINE 				# add yagna official completion engine
-# remove completion hooks to ensure overrides defined in this source
-complete -r -o bashdefault -o default -F _yagna yagna 2>/dev/null	# clear before reload of yagna official script
 if [[ $? != 0 ]]; then
-	echo "[[gc__enhanced_completion]] ERROR: could not parse yagna's completion engine"
+	echo "[[gc__enhanced_completion]] ERROR: could not load yagna's completion engine"
 	return
 fi
+source /dev/stdin <<<$YAGNA_COMPLETION_ENGINE 				# add yagna official completion engine
+if [[ $? != 0 ]]; then
+	echo "[[gc__enhanced_completion]] ERROR: could not load parse's completion engine"
+	return
+fi
+# remove completion hooks to ensure overrides defined in this source
+complete -r -o bashdefault -o default -F _yagna yagna 2>/dev/null	# clear before reload of yagna official script
 
 # check for internal support of golemsp completions
 GOLEMSP_COMPLETION_ENGINE_FULL=$(golemsp complete bash 2>&1)
@@ -30,7 +34,7 @@ if [[ $GOLEMSP_SUPPORTED ]]; then
 	if [[ $? != 0 ]]; then
 		echo "[[gc__enhanced_completion]] WARN: could not parse golemsp's completion engine"
 	fi
-else
+else # fallback to custom completion engine
 	gc__subcommands=(golemsp yagna run stop settings	set show)	# golemsp subcommands manually added
 fi
 
