always use completions provided by executables

diff --git a/gc_golem b/gc_golem
--- a/gc_golem
+++ b/gc_golem
@@ -1,5 +1,5 @@
 # gc_golem
-# version: 20251024_1
+# version: 20251026_1
 # golem completion engine
 # author: krunch3r76 (https://github.com/krunch3r76)
 # license: poetic/GPL 3
@@ -14,14 +14,19 @@ YAGNA_COMPLETION_ENGINE=$(yagna complete bash 2>&1)	# store the completion engin
 if [[ $? != 0 ]]; then
 	echo "[[gc__enhanced_completion]] ERROR: could not load yagna's completion engine"
 	return
+else
+	YAGNA_SUPPORTED=1
+	source /dev/stdin <<<$YAGNA_COMPLETION_ENGINE 				# add yagna official completion engine
+	if [[ $? != 0 ]]; then
+		echo "[[gc__enhanced_completion]] ERROR: could not yagna's parse's completion engine"
+	fi
 fi
-source /dev/stdin <<<$YAGNA_COMPLETION_ENGINE 				# add yagna official completion engine
-if [[ $? != 0 ]]; then
-	echo "[[gc__enhanced_completion]] ERROR: could not load parse's completion engine"
-	return
+
+
+if [[ $YAGNA_SUPPORTED ]]; then
+	# remove completion hooks to ensure overrides defined in this source
+	complete -r -o bashdefault -o default -F _yagna yagna 2>/dev/null	# clear before reload of yagna official script
 fi
-# remove completion hooks to ensure overrides defined in this source
-complete -r -o bashdefault -o default -F _yagna yagna 2>/dev/null	# clear before reload of yagna official script
 
 # check for internal support of golemsp completions
 GOLEMSP_COMPLETION_ENGINE_FULL=$(golemsp complete bash 2>&1)
@@ -31,11 +36,6 @@ if [[ $? == 0 ]]; then # command to get the completions ran successfully
 	# remove completion hooks to ensure overrides defined in this source
 	complete -r -o bashdefault -o default -F _golemsp golemsp 2>/dev/null	# clear before reload of golemsp official script
 	[[ $(declare -f _golemsp) ]] && GOLEMSP_SUPPORTED=1 # the expected completion function has been defined
-fi
-
-if [[ ! $GOLEMSP_SUPPORTED ]]; then
-#	echo "[[gc__enhanced_completion]] WARN: could not parse golemsp's completion engine, manually added"
-	gc__subcommands=(golemsp yagna run stop settings	set show)	# golemsp subcommands manually added
 fi
 
 
@@ -53,34 +53,6 @@ _gc__context_help() {
 	fi
 	echo -n "${PS1@P}$COMP_LINE"
 }
-
-
-
-
-
-# INPUT: last entered subcommand, second to last entered subcommand
-# OUTPUT: none
-# POST: COMPREPLY {global} set with possible completions
-_gc__completion_golemsp() {
-	# DOCSTRING: tab complete current word for command name golemsp
-	local ULTIMATE=$1
-	local PENULTIMATE=$2
-	local options
-	if [[ "$ULTIMATE" == "golemsp" ]]; then
-		options=(run stop settings status help)
-	elif [[ "$ULTIMATE" == "run" ]]; then
-		options=(--subnet --account --payment-network --log-dir --debug)
-	elif [[ "$ULTIMATE" == "settings" ]]; then
-		options=(set show)
-	elif [[ "$ULTIMATE" == "set" && $PENULTIMATE == "settings" ]]; then
-		options=(--node-name --cores --memory --disk --starting-fee --env-per-hour --cpu-per-hour --acount --payment-network)
-	fi
-	COMPREPLY=($(compgen -W "${options[*]}" \"${COMP_WORDS[$COMP_CWORD]}\")) # generate and use possible expansions in options from the word under the cursor
-}
-
-
-
-
 
 # INPUT: gc__cwords {global}
 # OUTPUT: space delimited tuple of size 1 or 2 containing ULTIMATE and if found PENULTIMATE
@@ -108,15 +80,6 @@ _gc__completion__rfind_subcommands() {
 	echo $ULTIMATE ${PENULTIMATE:+$PENULTIMATE}
 }
 
-
-
-
-
-
-
-
-
-
 # IN: complete's builtin exported variables
 # OUT: none
 # PRE: none
@@ -138,11 +101,13 @@ _gc__completion() {
 			if [[ $GOLEMSP_SUPPORTED ]]; then
 				_golemsp
  			else
-				_gc__completion_golemsp $ULTIMATE ${PENULTIMATE:+$PENULTIMATE}
+				# _gc__completion_golemsp $ULTIMATE ${PENULTIMATE:+$PENULTIMATE}
 			fi
 
 		elif [[ "$1" == "yagna" ]]; then
-			_yagna
+			if [[ $YAGNA_SUPPORTED ]]; then
+				_yagna
+			fi
 		fi
 	fi
 } && 
